### ISSUE TITLE
Compatibility with Julia 0.4

### ISSUE THREAD

**Issue by gbarz** [JuliaDB/PostgreSQL.jl#31]
Is there any estimated timeline for upgrading this package to be compatible with Julia 0.4x?

**Comment by iamed2** [comment]
My tests show that it is compatible with 0.4. Do you mean 0.5?

**Comment by gbarz** [comment]
It was for 0.4.

I was getting both warnings and errors after trying to move to 0.4.  Will double check update steps.

**Comment by iamed2** [comment]
There are currently known warnings, but there shouldn't be any errors. Please file an issue if you encounter an unexpected error :)

**Comment by MichaeLeroy** [comment]
I had a look at this issue when I was unable to load `PostgreSQL.jl`:

                   _
       _       _ _(_)_     |  A fresh approach to technical computing
      (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
       _ _   _| |_  __ _   |  Type "?help" for help.
      | | | | | | |/ _` |  |
      | | |_| | | | (_| |  |  Version 0.4.4-pre+35 (2016-02-12 13:21 UTC)
     _/ |\__'_|_|_|\__'_|  |  Commit 1a9429e (38 days old release-0.4)
    |__/                   |  x86_64-linux-gnu

    julia> using PostgreSQL
    ERROR: LoadError: ArgumentError: DBI not found in path
     in require at ./loading.jl:233
     in include at ./boot.jl:261
     in include_from_node1 at ./loading.jl:304
     in require at ./loading.jl:243
    while loading /home/mike/.julia/v0.4/PostgreSQL/src/PostgreSQL.jl, in expression starting on line 11

It didn't take too much work for me to conclude that the problem was one of missing the header files for `libpq`.  Fixing this (on an Ubuntu Linux machine) was a matter of installing the `libpq-dev` package:

    julia> using PostgreSQL
    
    julia> 

I have no idea whether this particular issue is what's troubling @gbarz but decided to add this comment in case it is helpful.

**Comment by PallHaraldsson** [comment]
Should this be closed by now..? I hope since I did: https://github.com/JuliaDB/PostgreSQL.jl/pull/43

**Comment by iamed2** [comment]
Yeah, especially as there was no specific issue mentioned here.
